"use client";

import { useState } from "react";

const modules = [
  { id: "mail", number: "01", name: "Mail Inspector", tag: "INBOX", icon: "✉", title: "A message worth questioning", type: "EMAIL ARTIFACT", content: "FROM       it-helpdesk@kku-support-login.com\nTO         you@kku.ac.th\nSUBJECT    URGENT — verify your account\nRECEIVED   08:41:22 / TODAY\n\nYour account will be suspended in 24 hours.\nVerify immediately: kku-support-login.com/verify?id=admin\n\nATTACHMENT  account_notice.html" },
  { id: "logs", number: "02", name: "Log Viewer", tag: "LOGS", icon: "⌁", title: "A quiet trail in the noise", type: "SERVER ARTIFACT", content: "01:42:11  LOGIN       user=admin   ip=185.22.14.8  SUCCESS\n01:42:18  MFA         user=admin   method=none\n01:43:08  DOWNLOAD    /database/users.csv      4.2MB\n01:44:19  LOGIN       user=student ip=10.24.1.19   SUCCESS\n01:44:23  SESSION_END user=student" },
  { id: "decode", number: "03", name: "Payload Decoder", tag: "DECODE", icon: "⌘", title: "Make the unreadable readable", type: "DATA ARTIFACT", content: "FORMAT     BASE64\nPAYLOAD    U0VDVVJJVFk=\n\nFORMAT     HEX\nPAYLOAD    5345435552495459\n\nBoth payloads point to the same word." },
];

export default function HackLab() {
  const [active, setActive] = useState(0); const [collected, setCollected] = useState<string[]>([]); const [exported, setExported] = useState(false); const module = modules[active];
  function collect() { if (!collected.includes(module.id)) setCollected([...collected, module.id]); }
  function exportCase() { window.localStorage.setItem("cyberescape-intel-code", `CE-KKU-${String(collected.length).padStart(2, "0")}-AWARE`); setExported(true); }
  return <main className="lab-app">
    <header className="lab-nav"><a href="/" className="lab-logo"><span>⌬</span><div>CYBERESCAPE<small>FIELD LAB / KKU-001</small></div></a><div className="lab-breadcrumb"><span>CASE 001</span><i>/</i><b>RESEARCH DESK</b></div><div className="lab-user"><span className="lab-live" /> SANDBOX MODE <a href="/">EXIT LAB ↗</a></div></header>
    <section className="lab-head"><div><p className="lab-kicker">AUTHORIZED ACCESS / TRAINING ONLY</p><h1>Find the<br /><i>signal.</i></h1><p className="lab-description">ยินดีต้อนรับสู่พื้นที่ค้นหาหลักฐาน<br />คุณไม่ได้กำลังแฮ็คระบบ — คุณกำลังฝึกสังเกตระบบ</p></div><div className="lab-mission-card"><span>CASE OBJECTIVE</span><strong>Build an evidence<br />package for the player.</strong><div><b>{collected.length}</b> / 03 artifacts collected</div></div></section>
    <div className="lab-workspace"><aside className="module-nav"><div className="module-nav-title"><span>RESEARCH MODULES</span><small>3 AVAILABLE</small></div>{modules.map((item, index) => <button key={item.id} className={active === index ? "active" : ""} onClick={() => { setActive(index); setExported(false); }}><span className="module-icon">{item.icon}</span><span><b>{item.name}</b><small>{item.tag} / MODULE {item.number}</small></span>{collected.includes(item.id) && <em>✓</em>}</button>)}<div className="lab-rule"><span>RULE 01</span><p>ทุกสิ่งในห้องนี้เป็นข้อมูลจำลองและอ่านได้อย่างปลอดภัย</p></div></aside><section className="artifact-view"><div className="artifact-toolbar"><span>ARTIFACT VIEWER / {module.type}</span><span>READ ONLY <i /></span></div><div className="artifact-heading"><span>{module.number}</span><div><h2>{module.title}</h2><p>{module.tag} / SIMULATED EVIDENCE</p></div></div><div className="artifact-frame"><div className="artifact-chrome"><span><i /><i /><i /></span><b>case://{module.id}/artifact</b><small>STATIC DATA</small></div><pre>{module.content}</pre><div className="scanline" /></div><div className="artifact-actions"><button onClick={collect} className={collected.includes(module.id) ? "collected" : ""}>{collected.includes(module.id) ? "✓ ADDED TO CASE" : "+ ADD TO CASE FILE"}</button><span>{collected.includes(module.id) ? "This artifact is ready for the case package." : "Make a note when you spot the important detail."}</span></div><div className="case-builder"><div><p>CASE PACKAGE</p><h3>{String(collected.length).padStart(2, "0")} <small>artifacts</small></h3></div><div className="artifact-pills">{collected.length ? collected.map(id => <b key={id}>{id.toUpperCase()}</b>) : <span>Empty — collect at least 2 artifacts</span>}</div><button disabled={collected.length < 2} onClick={exportCase}>{exported ? "PACKAGE EXPORTED ✓" : "EXPORT PACKAGE ↗"}</button></div>{exported && <div className="export-notice"><span>PACKAGE READY</span><strong>CE-KKU-{String(collected.length).padStart(2, "0")}-AWARE</strong><p>กลับไปหน้า Player แล้วกรอกรหัสใน Case Board</p></div>}</section></div><footer className="lab-footer"><span>CYBERESCAPE FIELD LAB / VERSION 0.1</span><span>SAFE SIMULATION • NO REAL TARGETS • EDUCATIONAL USE</span></footer>
  </main>;
}
