"use client";

import { useState } from "react";

const challenges = [
  { id: 1, tag: "WEB-01 / INSECURE DIRECT OBJECT REFERENCE", title: "The article nobody was supposed to read", text: "หน้า News แสดงบทความหนึ่งรายการ แต่ระบบดึงข้อมูลผ่าน API ลองดู Request ที่เกิดขึ้น แล้วหาวิธีเข้าถึงบทความที่ไม่แสดงบนหน้าเว็บ", target: "เป้าหมาย: ค้นหา Flag จากข้อมูล Article อื่น", answer: "FLAG{IDOR-ARTICLE-102}", hint: "ดูค่า id ใน Request แล้วลองเปลี่ยนเป็นเลขอื่น" },
  { id: 2, tag: "WEB-02 / PARAMETER TAMPERING", title: "A profile with more access", text: "หน้า Student Portal แสดงข้อมูลของนักศึกษาปัจจุบัน ลองวิเคราะห์ API และ parameter ที่ส่งไป เพื่อค้นหา profile ที่มีสิทธิ์สูงกว่า", target: "เป้าหมาย: ค้นหา Flag จาก profile ของ admin", answer: "FLAG{PARAM-ROLE-ADMIN-001}", hint: "ลองสังเกตค่า id และ role ใน Request" },
  { id: 3, tag: "WEB-03 / INFORMATION DISCLOSURE", title: "The search result says too much", text: "ระบบ Search ส่งผลลัพธ์กลับมาเป็น JSON ลองดู Response ทั้งหมด ไม่ใช่แค่สิ่งที่หน้าเว็บแสดง", target: "เป้าหมาย: ค้นหา Flag ที่รั่วอยู่ใน API Response", answer: "FLAG{API-RESPONSE-LEAK}", hint: "เปิดดู Response body ของ Search API ให้ครบ" },
];

export default function AnswerWeb() {
  const [active, setActive] = useState(0); const [value, setValue] = useState(""); const [status, setStatus] = useState<"idle" | "correct" | "wrong">("idle"); const challenge = challenges[active];
  function submit() { setStatus(value.trim().toUpperCase() === challenge.answer ? "correct" : "wrong"); }
  function choose(index: number) { setActive(index); setValue(""); setStatus("idle"); }
  return <main className="answer-app"><header className="answer-nav"><a href="/" className="answer-logo"><span>01</span><div>BREACH / RESPONSE<small>SECURITY AWARENESS CHALLENGE</small></div></a><div className="answer-links"><span>PLAYER: GUEST</span><a href="/target">OPEN TARGET WEBSITE ↗</a></div></header><section className="answer-intro"><p className="answer-kicker">MISSION CONTROL / SUBMIT YOUR FINDINGS</p><h1>Find it.<br /><i>Prove it.</i></h1><p>คำตอบที่ถูกต้องไม่ได้อยู่ในหน้านี้<br />เปิด Target Website แล้วค้นหาหลักฐานจาก API</p><a className="target-button" href="/target">GO TO TARGET WEBSITE <span>↗</span></a></section><div className="answer-grid"><aside className="challenge-nav"><div className="answer-section-label">CHALLENGES <b>0{challenges.length}</b></div>{challenges.map((item, index) => <button key={item.id} className={active === index ? "active" : ""} onClick={() => choose(index)}><span>0{item.id}</span><div><b>{item.title}</b><small>{item.tag}</small></div><em>{active === index ? "OPEN" : ""}</em></button>)}<div className="rules"><span>HOW TO PLAY</span><ol><li>เปิด Target Website</li><li>ใช้ DevTools / Network</li><li>หา Flag จาก API</li><li>นำ Flag กลับมาตอบ</li></ol></div></aside><section className="question-panel"><div className="question-meta"><span>{challenge.tag}</span><span>QUESTION {challenge.id} / 03</span></div><h2>{challenge.title}</h2><p className="question-text">{challenge.text}</p><div className="objective"><span>OBJECTIVE</span><b>{challenge.target}</b></div><label>SUBMIT FLAG <small>CASE SENSITIVE: NO</small></label><div className="flag-input"><input value={value} onChange={e => { setValue(e.target.value); setStatus("idle"); }} onKeyDown={e => e.key === "Enter" && submit()} placeholder="FLAG{...}" /><button onClick={submit}>SUBMIT</button></div>{status !== "idle" && <div className={`answer-status ${status}`}>{status === "correct" ? "✓ FLAG ACCEPTED — challenge complete" : "× FLAG REJECTED — keep investigating"}</div>}<div className="question-footer"><button onClick={() => alert(challenge.hint)}>SHOW HINT</button><span>Hint does not reveal the answer</span></div></section><aside className="score-panel"><span>SESSION SCORE</span><strong>{active * 100 + (status === "correct" ? 100 : 0)}</strong><small>POINTS</small><div className="score-line"><i style={{ width: `${status === "correct" ? 100 : 0}%` }} /></div><p>Complete all three challenges to finish the case.</p></aside></div><footer className="answer-footer"><span>BREACH / RESPONSE</span><span>CONTROLLED EDUCATIONAL SIMULATION — NO REAL TARGETS</span></footer></main>;
}
